"""
Seed script: populate the hospitals table with realistic mock data
for Lublin voivodeship based on analysis spec 3.3 (NFZ/MZ).

Run: python seed_hospitals.py
"""
import asyncio

from sqlalchemy import delete

from database import engine, Base, HospitalRow, SessionLocal


HOSPITALS: list[dict] = [
    # ── Lublin — duże szpitale kliniczne / wojewódzkie ───────────────────────
    {
        "facility_id": "LUB-001",
        "name": "Uniwersytecki Szpital Kliniczny nr 1 w Lublinie",
        "short_name": "USK1 Lublin",
        "type": "szpital_kliniczny",
        "operator": "Uniwersytet Medyczny w Lublinie",
        "nfz_contract": True,
        "street": "ul. Staszica 16",
        "city": "Lublin",
        "postal_code": "20-081",
        "gmina": "Lublin",
        "powiat": "Lublin",
        "teryt_code": "0663011",
        "latitude": 51.251364,
        "longitude": 22.563652,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 120,
        "decontamination_entry": True,
        "isolation_rooms": 6,
        "negative_pressure_rooms": 3,
        "beds_total_contracted": 680,
        "beds_total_physical": 720,
        "beds_occupied_pct": 0.74,
        "beds_available_estimate": 187,
        "icu_oiom_beds": 24,
        "ventilator_capable_beds": 18,
        "ecmo_available": True,
        "dialysis_stations": 12,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 14,
        "polytrauma_capable": True,
        "ct_24_7": True,
        "mri_available": True,
        "helipad": True,
        "helipad_type": "na_dachu",
        "helipad_night_capable": True,
        "backup_power": True,
        "backup_power_fuel_hours": 72.0,
        "phone_24h_sor": "+48 81 532 39 22",
        "email": "sekretariat@usk1.lublin.pl",
        "specializations": "kardiologia,chirurgia ogólna,neurologia,nefrologia,onkologia,ortopedia,urologia",
    },
    {
        "facility_id": "LUB-002",
        "name": "Uniwersytecki Szpital Kliniczny Nr 4 w Lublinie",
        "short_name": "USK4 Lublin",
        "type": "szpital_kliniczny",
        "operator": "Uniwersytet Medyczny w Lublinie",
        "nfz_contract": True,
        "street": "ul. Jaczewskiego 8",
        "city": "Lublin",
        "postal_code": "20-954",
        "gmina": "Lublin",
        "powiat": "Lublin",
        "teryt_code": "0663011",
        "latitude": 51.258879,
        "longitude": 22.564937,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 95,
        "decontamination_entry": True,
        "isolation_rooms": 4,
        "negative_pressure_rooms": 2,
        "beds_total_contracted": 560,
        "beds_total_physical": 600,
        "beds_occupied_pct": 0.71,
        "beds_available_estimate": 174,
        "icu_oiom_beds": 20,
        "ventilator_capable_beds": 16,
        "ecmo_available": True,
        "dialysis_stations": 10,
        "burn_unit": True,
        "neonatal_icu": True,
        "operating_rooms": 12,
        "polytrauma_capable": True,
        "ct_24_7": True,
        "mri_available": True,
        "helipad": True,
        "helipad_type": "na_dachu",
        "helipad_night_capable": True,
        "backup_power": True,
        "backup_power_fuel_hours": 72.0,
        "phone_24h_sor": "+48 81 724 41 54",
        "email": "sekretariat@usk4.lublin.pl",
        "specializations": "chirurgia urazowa,kardiochirurgia,neurochirurgia,toksykologia,neonatologia,transplantologia",
    },
    {
        "facility_id": "LUB-003",
        "name": "Uniwersytecki Szpital Dziecięcy w Lublinie",
        "short_name": "USD Lublin",
        "type": "szpital_kliniczny",
        "operator": "Uniwersytet Medyczny w Lublinie",
        "nfz_contract": True,
        "street": "ul. Prof. Antoniego Gębali 6",
        "city": "Lublin",
        "postal_code": "20-093",
        "gmina": "Lublin",
        "powiat": "Lublin",
        "teryt_code": "0663011",
        "latitude": 51.26036,
        "longitude": 22.561033,
        "has_sor": True,
        "has_pediatric_sor": True,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 65,
        "decontamination_entry": False,
        "isolation_rooms": 4,
        "negative_pressure_rooms": 2,
        "beds_total_contracted": 340,
        "beds_total_physical": 360,
        "beds_occupied_pct": 0.68,
        "beds_available_estimate": 115,
        "icu_oiom_beds": 12,
        "ventilator_capable_beds": 10,
        "ecmo_available": False,
        "dialysis_stations": 4,
        "burn_unit": False,
        "neonatal_icu": True,
        "operating_rooms": 6,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": True,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": True,
        "backup_power": True,
        "backup_power_fuel_hours": 48.0,
        "phone_24h_sor": "+48 81 718 54 00",
        "email": "sekretariat@usd.lublin.pl",
        "specializations": "pediatria,chirurgia dziecięca,neonatologia,kardiologia dziecięca,onkologia dziecięca",
    },
    {
        "facility_id": "LUB-004",
        "name": "Wojewódzki Szpital Specjalistyczny im. Kard. Stefana Wyszyńskiego SPZOZ w Lublinie",
        "short_name": "WSS Lublin",
        "type": "szpital_specjalistyczny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "al. Kraśnicka 100",
        "city": "Lublin",
        "postal_code": "20-718",
        "gmina": "Lublin",
        "powiat": "Lublin",
        "teryt_code": "0663011",
        "latitude": 51.239288,
        "longitude": 22.50414,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 110,
        "decontamination_entry": True,
        "isolation_rooms": 5,
        "negative_pressure_rooms": 2,
        "beds_total_contracted": 740,
        "beds_total_physical": 780,
        "beds_occupied_pct": 0.76,
        "beds_available_estimate": 187,
        "icu_oiom_beds": 22,
        "ventilator_capable_beds": 16,
        "ecmo_available": True,
        "dialysis_stations": 14,
        "burn_unit": False,
        "neonatal_icu": True,
        "operating_rooms": 15,
        "polytrauma_capable": True,
        "ct_24_7": True,
        "mri_available": True,
        "helipad": True,
        "helipad_type": "na_dachu",
        "helipad_night_capable": True,
        "backup_power": True,
        "backup_power_fuel_hours": 72.0,
        "phone_24h_sor": "+48 81 537 44 71",
        "email": "sekretariat@wss.lublin.pl",
        "specializations": "kardiologia,neurologia,chirurgia naczyniowa,onkologia,ortopedia,okulistyka,urologia,gastroenterologia",
    },
    {
        "facility_id": "LUB-005",
        "name": "Centrum Onkologii Ziemi Lubelskiej im. św. Jana z Dukli",
        "short_name": "COZL Lublin",
        "type": "szpital_specjalistyczny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Jaczewskiego 7",
        "city": "Lublin",
        "postal_code": "20-090",
        "gmina": "Lublin",
        "powiat": "Lublin",
        "teryt_code": "0663011",
        "latitude": 51.257886,
        "longitude": 22.567508,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 25,
        "decontamination_entry": False,
        "isolation_rooms": 3,
        "negative_pressure_rooms": 1,
        "beds_total_contracted": 420,
        "beds_total_physical": 450,
        "beds_occupied_pct": 0.82,
        "beds_available_estimate": 81,
        "icu_oiom_beds": 8,
        "ventilator_capable_beds": 6,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 8,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": True,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 48.0,
        "phone_24h_sor": "+48 81 454 11 02",
        "email": "sekretariat@cozl.eu",
        "specializations": "onkologia kliniczna,radioterapia,chirurgia onkologiczna,hematologia,brachyterapia",
    },
    {
        "facility_id": "LUB-006",
        "name": "I Wojskowy Szpital Kliniczny z Polikliniką SPZOZ w Lublinie",
        "short_name": "1WSK Lublin",
        "type": "szpital_kliniczny",
        "operator": "MON / SPZOZ",
        "nfz_contract": True,
        "street": "al. Racławickie 23",
        "city": "Lublin",
        "postal_code": "20-049",
        "gmina": "Lublin",
        "powiat": "Lublin",
        "teryt_code": "0663011",
        "latitude": 51.2515,
        "longitude": 22.534465,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 85,
        "decontamination_entry": True,
        "isolation_rooms": 4,
        "negative_pressure_rooms": 2,
        "beds_total_contracted": 480,
        "beds_total_physical": 520,
        "beds_occupied_pct": 0.69,
        "beds_available_estimate": 161,
        "icu_oiom_beds": 16,
        "ventilator_capable_beds": 12,
        "ecmo_available": False,
        "dialysis_stations": 8,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 10,
        "polytrauma_capable": True,
        "ct_24_7": True,
        "mri_available": True,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": True,
        "backup_power": True,
        "backup_power_fuel_hours": 96.0,
        "phone_24h_sor": "+48 81 261 16 00",
        "email": "kancelaria@1wsk.lublin.pl",
        "specializations": "chirurgia ogólna,ortopedia,kardiologia,neurologia,okulistyka,laryngologia",
    },
    {
        "facility_id": "LUB-007",
        "name": "SPZOZ MSWiA w Lublinie",
        "short_name": "MSWiA Lublin",
        "type": "szpital_ogólny",
        "operator": "MSWiA",
        "nfz_contract": True,
        "street": "ul. Grenadierów 3",
        "city": "Lublin",
        "postal_code": "20-331",
        "gmina": "Lublin",
        "powiat": "Lublin",
        "teryt_code": "0663011",
        "latitude": 51.226843,
        "longitude": 22.614373,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 45,
        "decontamination_entry": False,
        "isolation_rooms": 2,
        "negative_pressure_rooms": 1,
        "beds_total_contracted": 180,
        "beds_total_physical": 200,
        "beds_occupied_pct": 0.65,
        "beds_available_estimate": 70,
        "icu_oiom_beds": 6,
        "ventilator_capable_beds": 4,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 4,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 81 728 56 00",
        "email": "sekretariat@szpitalmsw.lublin.pl",
        "specializations": "interna,chirurgia ogólna,ortopedia,rehabilitacja",
    },
    {
        "facility_id": "LUB-008",
        "name": "Szpital im. Jana Bożego w Lublinie",
        "short_name": "Szp. Jana Bożego",
        "type": "szpital_ogólny",
        "operator": "Zakon Bonifratrów / SPZOZ",
        "nfz_contract": True,
        "street": "ul. Biernackiego 9",
        "city": "Lublin",
        "postal_code": "20-089",
        "gmina": "Lublin",
        "powiat": "Lublin",
        "teryt_code": "0663011",
        "latitude": 51.215453,
        "longitude": 22.570005,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 30,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 140,
        "beds_total_physical": 160,
        "beds_occupied_pct": 0.72,
        "beds_available_estimate": 45,
        "icu_oiom_beds": 4,
        "ventilator_capable_beds": 3,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 3,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 81 740 86 00",
        "email": "szpital@bonifratrzy.lublin.pl",
        "specializations": "interna,chirurgia ogólna,geriatria,rehabilitacja",
    },
    {
        "facility_id": "LUB-009",
        "name": "Instytut Medycyny Wsi im. Witolda Chodźki w Lublinie",
        "short_name": "IMW Lublin",
        "type": "szpital_specjalistyczny",
        "operator": "Instytut Badawczy",
        "nfz_contract": True,
        "street": "ul. Jaczewskiego 2",
        "city": "Lublin",
        "postal_code": "20-090",
        "gmina": "Lublin",
        "powiat": "Lublin",
        "teryt_code": "0663011",
        "latitude": 51.256175,
        "longitude": 22.563012,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 20,
        "decontamination_entry": False,
        "isolation_rooms": 2,
        "negative_pressure_rooms": 1,
        "beds_total_contracted": 200,
        "beds_total_physical": 220,
        "beds_occupied_pct": 0.60,
        "beds_available_estimate": 88,
        "icu_oiom_beds": 4,
        "ventilator_capable_beds": 3,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 4,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": True,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 36.0,
        "phone_24h_sor": "+48 81 718 44 00",
        "email": "imw@imw.lublin.pl",
        "specializations": "medycyna pracy,toksykologia kliniczna,choroby zakaźne,pulmonologia",
    },
    {
        "facility_id": "LUB-010",
        "name": "Żagiel Med Szpital w Lublinie",
        "short_name": "Żagiel Med",
        "type": "szpital_ogólny",
        "operator": "Żagiel Med Sp. z o.o.",
        "nfz_contract": True,
        "street": "ul. Nałęczowska 27",
        "city": "Lublin",
        "postal_code": "20-701",
        "gmina": "Lublin",
        "powiat": "Lublin",
        "teryt_code": "0663011",
        "latitude": 51.225844,
        "longitude": 22.595069,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 15,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 80,
        "beds_total_physical": 95,
        "beds_occupied_pct": 0.58,
        "beds_available_estimate": 40,
        "icu_oiom_beds": 2,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 3,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": True,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 12.0,
        "phone_24h_sor": "+48 81 524 68 00",
        "email": "recepcja@zagielmed.pl",
        "specializations": "ortopedia,chirurgia ogólna,ginekologia,okulistyka",
    },
    # ── Lublin — szpitale psychiatryczne ─────────────────────────────────────
    {
        "facility_id": "LUB-011",
        "name": "Szpital Neuropsychiatryczny im. prof. Mieczysława Kaczyńskiego w Lublinie",
        "short_name": "Neuropsych. Lublin",
        "type": "szpital_specjalistyczny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Abramowicka 2",
        "city": "Lublin",
        "postal_code": "20-442",
        "gmina": "Lublin",
        "powiat": "Lublin",
        "teryt_code": "0663011",
        "latitude": 51.204718,
        "longitude": 22.589652,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 15,
        "decontamination_entry": False,
        "isolation_rooms": 3,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 350,
        "beds_total_physical": 380,
        "beds_occupied_pct": 0.85,
        "beds_available_estimate": 57,
        "icu_oiom_beds": 2,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 1,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 81 744 09 10",
        "email": "sekretariat@snzoz.lublin.pl",
        "specializations": "psychiatria,neurologia,psychogeriatria,leczenie uzależnień",
    },
    # ── Zamość ────────────────────────────────────────────────────────────────
    {
        "facility_id": "ZAM-001",
        "name": "Samodzielny Publiczny Szpital Wojewódzki im. Papieża Jana Pawła II w Zamościu",
        "short_name": "Szp. Woj. Zamość",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Aleje Jana Pawła II 10",
        "city": "Zamość",
        "postal_code": "22-400",
        "gmina": "Zamość",
        "powiat": "zamojski",
        "teryt_code": "0664011",
        "latitude": 50.712785,
        "longitude": 23.289005,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 75,
        "decontamination_entry": True,
        "isolation_rooms": 4,
        "negative_pressure_rooms": 2,
        "beds_total_contracted": 580,
        "beds_total_physical": 620,
        "beds_occupied_pct": 0.73,
        "beds_available_estimate": 167,
        "icu_oiom_beds": 14,
        "ventilator_capable_beds": 10,
        "ecmo_available": False,
        "dialysis_stations": 10,
        "burn_unit": False,
        "neonatal_icu": True,
        "operating_rooms": 10,
        "polytrauma_capable": True,
        "ct_24_7": True,
        "mri_available": True,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": True,
        "backup_power": True,
        "backup_power_fuel_hours": 48.0,
        "phone_24h_sor": "+48 84 677 33 33",
        "email": "sekretariat@szpital.zamosc.pl",
        "specializations": "kardiologia,chirurgia ogólna,neurologia,ortopedia,ginekologia,neonatologia,urologia",
    },
    {
        "facility_id": "ZAM-002",
        "name": "Zamojski Szpital Niepubliczny Sp. z o.o.",
        "short_name": "Szp. Niepubl. Zamość",
        "type": "szpital_ogólny",
        "operator": "Zamojski Szpital Niepubliczny Sp. z o.o.",
        "nfz_contract": True,
        "street": "ul. Peowiaków 1",
        "city": "Zamość",
        "postal_code": "22-400",
        "gmina": "Zamość",
        "powiat": "zamojski",
        "teryt_code": "0664011",
        "latitude": 50.723925,
        "longitude": 23.254578,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 20,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 120,
        "beds_total_physical": 140,
        "beds_occupied_pct": 0.62,
        "beds_available_estimate": 53,
        "icu_oiom_beds": 3,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 3,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 18.0,
        "phone_24h_sor": "+48 84 638 80 00",
        "email": "biuro@szpitalzamosc.pl",
        "specializations": "interna,chirurgia ogólna,ginekologia,rehabilitacja",
    },
    # ── Chełm ────────────────────────────────────────────────────────────────
    {
        "facility_id": "CHE-001",
        "name": "Samodzielny Publiczny Wojewódzki Szpital Specjalistyczny w Chełmie",
        "short_name": "Szp. Woj. Chełm",
        "type": "szpital_specjalistyczny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Ceramiczna 1",
        "city": "Chełm",
        "postal_code": "22-100",
        "gmina": "Chełm",
        "powiat": "chełmski",
        "teryt_code": "0662011",
        "latitude": 51.150349,
        "longitude": 23.455444,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 60,
        "decontamination_entry": True,
        "isolation_rooms": 3,
        "negative_pressure_rooms": 1,
        "beds_total_contracted": 420,
        "beds_total_physical": 460,
        "beds_occupied_pct": 0.70,
        "beds_available_estimate": 138,
        "icu_oiom_beds": 10,
        "ventilator_capable_beds": 8,
        "ecmo_available": False,
        "dialysis_stations": 8,
        "burn_unit": False,
        "neonatal_icu": True,
        "operating_rooms": 8,
        "polytrauma_capable": True,
        "ct_24_7": True,
        "mri_available": True,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": True,
        "backup_power": True,
        "backup_power_fuel_hours": 48.0,
        "phone_24h_sor": "+48 82 562 35 80",
        "email": "sekretariat@szpital.chelm.pl",
        "specializations": "kardiologia,chirurgia ogólna,neurologia,ortopedia,ginekologia,neonatologia",
    },
    # ── Biała Podlaska ────────────────────────────────────────────────────────
    {
        "facility_id": "BPD-001",
        "name": "Wojewódzki Szpital Specjalistyczny w Białej Podlaskiej",
        "short_name": "WSS Biała Podlaska",
        "type": "szpital_specjalistyczny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Terebelska 57-65",
        "city": "Biała Podlaska",
        "postal_code": "21-500",
        "gmina": "Biała Podlaska",
        "powiat": "bialski",
        "teryt_code": "0661011",
        "latitude": 52.046725,
        "longitude": 23.112013,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 70,
        "decontamination_entry": True,
        "isolation_rooms": 3,
        "negative_pressure_rooms": 1,
        "beds_total_contracted": 460,
        "beds_total_physical": 500,
        "beds_occupied_pct": 0.72,
        "beds_available_estimate": 140,
        "icu_oiom_beds": 12,
        "ventilator_capable_beds": 10,
        "ecmo_available": False,
        "dialysis_stations": 8,
        "burn_unit": False,
        "neonatal_icu": True,
        "operating_rooms": 8,
        "polytrauma_capable": True,
        "ct_24_7": True,
        "mri_available": True,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": True,
        "backup_power": True,
        "backup_power_fuel_hours": 48.0,
        "phone_24h_sor": "+48 83 414 71 00",
        "email": "sekretariat@szpitalbp.pl",
        "specializations": "kardiologia,chirurgia ogólna,neurologia,ortopedia,ginekologia,neonatologia,urologia",
    },
    # ── Puławy ────────────────────────────────────────────────────────────────
    {
        "facility_id": "PUL-001",
        "name": "SPZOZ Szpital Specjalistyczny w Puławach",
        "short_name": "Szp. Puławy",
        "type": "szpital_specjalistyczny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Bema 1",
        "city": "Puławy",
        "postal_code": "24-100",
        "gmina": "Puławy",
        "powiat": "puławski",
        "teryt_code": "0614011",
        "latitude": 51.421252,
        "longitude": 21.973314,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 55,
        "decontamination_entry": True,
        "isolation_rooms": 3,
        "negative_pressure_rooms": 1,
        "beds_total_contracted": 380,
        "beds_total_physical": 410,
        "beds_occupied_pct": 0.71,
        "beds_available_estimate": 119,
        "icu_oiom_beds": 10,
        "ventilator_capable_beds": 8,
        "ecmo_available": False,
        "dialysis_stations": 6,
        "burn_unit": False,
        "neonatal_icu": True,
        "operating_rooms": 6,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": True,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": True,
        "backup_power": True,
        "backup_power_fuel_hours": 48.0,
        "phone_24h_sor": "+48 81 886 40 01",
        "email": "sekretariat@szpitalpulawy.pl",
        "specializations": "kardiologia,chirurgia ogólna,neurologia,ortopedia,ginekologia,neonatologia,toksykologia",
    },
    # ── Szpitale powiatowe ────────────────────────────────────────────────────
    {
        "facility_id": "KRS-001",
        "name": "Szpital Powiatowy w Kraśniku SPZOZ",
        "short_name": "Szp. Kraśnik",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Chopina 13",
        "city": "Kraśnik",
        "postal_code": "23-200",
        "gmina": "Kraśnik",
        "powiat": "kraśnicki",
        "teryt_code": "0607011",
        "latitude": 50.932417,
        "longitude": 22.22344,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 40,
        "decontamination_entry": False,
        "isolation_rooms": 2,
        "negative_pressure_rooms": 1,
        "beds_total_contracted": 220,
        "beds_total_physical": 240,
        "beds_occupied_pct": 0.68,
        "beds_available_estimate": 77,
        "icu_oiom_beds": 6,
        "ventilator_capable_beds": 4,
        "ecmo_available": False,
        "dialysis_stations": 4,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 4,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": False,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 81 825 13 14",
        "email": "sekretariat@spzozkrasnik.pl",
        "specializations": "interna,chirurgia ogólna,ortopedia,ginekologia,pediatria",
    },
    {
        "facility_id": "BLG-001",
        "name": "Arion Szpitale — Zespół Opieki Zdrowotnej w Biłgoraju",
        "short_name": "Szp. Biłgoraj",
        "type": "szpital_ogólny",
        "operator": "ARION Szpitale Sp. z o.o.",
        "nfz_contract": True,
        "street": "ul. Pojaska 11",
        "city": "Biłgoraj",
        "postal_code": "23-400",
        "gmina": "Biłgoraj",
        "powiat": "biłgorajski",
        "teryt_code": "0601011",
        "latitude": 50.529011,
        "longitude": 22.713089,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 35,
        "decontamination_entry": False,
        "isolation_rooms": 2,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 200,
        "beds_total_physical": 220,
        "beds_occupied_pct": 0.66,
        "beds_available_estimate": 75,
        "icu_oiom_beds": 5,
        "ventilator_capable_beds": 4,
        "ecmo_available": False,
        "dialysis_stations": 4,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 3,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": False,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 84 688 22 01",
        "email": "biuro@arion-bilgoraj.pl",
        "specializations": "interna,chirurgia ogólna,ortopedia,ginekologia,pediatria",
    },
    {
        "facility_id": "TLB-001",
        "name": "SPZOZ w Tomaszowie Lubelskim",
        "short_name": "Szp. Tomaszów Lub.",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Aleje Grunwaldzkie 1",
        "city": "Tomaszów Lubelski",
        "postal_code": "22-600",
        "gmina": "Tomaszów Lubelski",
        "powiat": "tomaszowski",
        "teryt_code": "0618011",
        "latitude": 50.442339,
        "longitude": 23.41593,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 30,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 180,
        "beds_total_physical": 200,
        "beds_occupied_pct": 0.64,
        "beds_available_estimate": 72,
        "icu_oiom_beds": 4,
        "ventilator_capable_beds": 3,
        "ecmo_available": False,
        "dialysis_stations": 4,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 3,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": False,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 84 664 44 11",
        "email": "sekretariat@szpital-tomaszow.pl",
        "specializations": "interna,chirurgia ogólna,ortopedia,ginekologia,pediatria",
    },
    {
        "facility_id": "HRB-001",
        "name": "Szpital Powiatowy im. Świętej Jadwigi Królowej w Hrubieszowie",
        "short_name": "Szp. Hrubieszów",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Piłsudskiego 11",
        "city": "Hrubieszów",
        "postal_code": "22-500",
        "gmina": "Hrubieszów",
        "powiat": "hrubieszowski",
        "teryt_code": "0604011",
        "latitude": 50.80119,
        "longitude": 23.893428,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 25,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 150,
        "beds_total_physical": 170,
        "beds_occupied_pct": 0.60,
        "beds_available_estimate": 68,
        "icu_oiom_beds": 4,
        "ventilator_capable_beds": 3,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": False,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 84 696 25 71",
        "email": "sekretariat@szpital-hrubieszow.pl",
        "specializations": "interna,chirurgia ogólna,ginekologia,pediatria",
    },
    {
        "facility_id": "WLD-001",
        "name": "Samodzielny Publiczny Zespół Opieki Zdrowotnej we Włodawie",
        "short_name": "Szp. Włodawa",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "al. J. Piłsudskiego 64",
        "city": "Włodawa",
        "postal_code": "22-200",
        "gmina": "Włodawa",
        "powiat": "włodawski",
        "teryt_code": "0619011",
        "latitude": 51.556868,
        "longitude": 23.554764,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 20,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 130,
        "beds_total_physical": 150,
        "beds_occupied_pct": 0.58,
        "beds_available_estimate": 63,
        "icu_oiom_beds": 3,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 18.0,
        "phone_24h_sor": "+48 82 572 12 46",
        "email": "sekretariat@spzoz.wlodawa.pl",
        "specializations": "interna,chirurgia ogólna,ginekologia,pediatria",
    },
    {
        "facility_id": "LBR-001",
        "name": "Szpital Powiatowy w Lubartowie SPZOZ",
        "short_name": "Szp. Lubartów",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Cicha 14",
        "city": "Lubartów",
        "postal_code": "21-100",
        "gmina": "Lubartów",
        "powiat": "lubartowski",
        "teryt_code": "0608011",
        "latitude": 51.456319,
        "longitude": 22.618388,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 30,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 180,
        "beds_total_physical": 200,
        "beds_occupied_pct": 0.67,
        "beds_available_estimate": 66,
        "icu_oiom_beds": 4,
        "ventilator_capable_beds": 3,
        "ecmo_available": False,
        "dialysis_stations": 4,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 3,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": False,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 81 855 23 56",
        "email": "sekretariat@spzoz-lubartow.pl",
        "specializations": "interna,chirurgia ogólna,ortopedia,ginekologia,pediatria",
    },
    {
        "facility_id": "PRC-001",
        "name": "Szpital Powiatowy w Parczewie SPZOZ",
        "short_name": "Szp. Parczew",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Szpitalna 1",
        "city": "Parczew",
        "postal_code": "21-200",
        "gmina": "Parczew",
        "powiat": "parczewski",
        "teryt_code": "0613011",
        "latitude": 51.633607,
        "longitude": 22.912863,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 20,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 120,
        "beds_total_physical": 140,
        "beds_occupied_pct": 0.60,
        "beds_available_estimate": 56,
        "icu_oiom_beds": 3,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 18.0,
        "phone_24h_sor": "+48 83 355 12 30",
        "email": "sekretariat@spzoz-parczew.pl",
        "specializations": "interna,chirurgia ogólna,ginekologia,pediatria",
    },
    {
        "facility_id": "RYK-001",
        "name": "Szpital Powiatowy w Rykach SPZOZ",
        "short_name": "Szp. Ryki",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Żytnia 23",
        "city": "Ryki",
        "postal_code": "08-500",
        "gmina": "Ryki",
        "powiat": "rycki",
        "teryt_code": "0615011",
        "latitude": 51.621438,
        "longitude": 21.92993,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 15,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 100,
        "beds_total_physical": 120,
        "beds_occupied_pct": 0.55,
        "beds_available_estimate": 54,
        "icu_oiom_beds": 2,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 18.0,
        "phone_24h_sor": "+48 81 865 13 60",
        "email": "sekretariat@spzoz-ryki.pl",
        "specializations": "interna,chirurgia ogólna,ginekologia",
    },
    {
        "facility_id": "LUK-001",
        "name": "Szpital Powiatowy im. św. Tadeusza w Łukowie SPZOZ",
        "short_name": "Szp. Łuków",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Dr. Andrzeja Rogalińskiego 3",
        "city": "Łuków",
        "postal_code": "21-400",
        "gmina": "Łuków",
        "powiat": "łukowski",
        "teryt_code": "0610011",
        "latitude": 51.924267,
        "longitude": 22.380513,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 35,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 200,
        "beds_total_physical": 220,
        "beds_occupied_pct": 0.66,
        "beds_available_estimate": 75,
        "icu_oiom_beds": 5,
        "ventilator_capable_beds": 4,
        "ecmo_available": False,
        "dialysis_stations": 4,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 3,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": False,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 25 798 20 01",
        "email": "sekretariat@spzoz-lukow.pl",
        "specializations": "interna,chirurgia ogólna,ortopedia,ginekologia,pediatria",
    },
    {
        "facility_id": "RDP-001",
        "name": "Szpital Powiatowy w Radzyniu Podlaskim SPZOZ",
        "short_name": "Szp. Radzyń Podl.",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Wisznicka 111",
        "city": "Radzyń Podlaski",
        "postal_code": "21-300",
        "gmina": "Radzyń Podlaski",
        "powiat": "radzyński",
        "teryt_code": "0615011",
        "latitude": 51.771121,
        "longitude": 22.607482,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 25,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 160,
        "beds_total_physical": 180,
        "beds_occupied_pct": 0.63,
        "beds_available_estimate": 67,
        "icu_oiom_beds": 4,
        "ventilator_capable_beds": 3,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 3,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": False,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 83 413 22 16",
        "email": "sekretariat@spzoz-radzyn.pl",
        "specializations": "interna,chirurgia ogólna,ortopedia,ginekologia,pediatria",
    },
    {
        "facility_id": "MRP-001",
        "name": "Szpital Powiatowy w Międzyrzecu Podlaskim SPZOZ",
        "short_name": "Szp. Międzyrzec",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Warszawska 2",
        "city": "Międzyrzec Podlaski",
        "postal_code": "21-560",
        "gmina": "Międzyrzec Podlaski",
        "powiat": "bialski",
        "teryt_code": "0602011",
        "latitude": 51.98472,
        "longitude": 22.787437,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 18,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 130,
        "beds_total_physical": 150,
        "beds_occupied_pct": 0.60,
        "beds_available_estimate": 60,
        "icu_oiom_beds": 3,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 18.0,
        "phone_24h_sor": "+48 83 371 83 01",
        "email": "sekretariat@spzoz-miedzyrzec.pl",
        "specializations": "interna,chirurgia ogólna,ginekologia",
    },
    {
        "facility_id": "LCZ-001",
        "name": "Szpital Powiatowy w Łęcznej SPZOZ",
        "short_name": "Szp. Łęczna",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Krasnystawska 52",
        "city": "Łęczna",
        "postal_code": "21-010",
        "gmina": "Łęczna",
        "powiat": "łęczyński",
        "teryt_code": "0609011",
        "latitude": 51.290876,
        "longitude": 22.878202,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 20,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 150,
        "beds_total_physical": 170,
        "beds_occupied_pct": 0.62,
        "beds_available_estimate": 65,
        "icu_oiom_beds": 3,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 18.0,
        "phone_24h_sor": "+48 81 752 63 01",
        "email": "sekretariat@spzoz-leczna.pl",
        "specializations": "interna,chirurgia ogólna,ginekologia,rehabilitacja",
    },
    {
        "facility_id": "JNW-001",
        "name": "Szpital Powiatowy w Janowie Lubelskim SPZZOZ",
        "short_name": "Szp. Janów Lub.",
        "type": "szpital_ogólny",
        "operator": "SPZZOZ",
        "nfz_contract": True,
        "street": "ul. Zamoyskiego 149",
        "city": "Janów Lubelski",
        "postal_code": "23-300",
        "gmina": "Janów Lubelski",
        "powiat": "janowski",
        "teryt_code": "0605011",
        "latitude": 50.702568,
        "longitude": 22.434098,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 22,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 140,
        "beds_total_physical": 160,
        "beds_occupied_pct": 0.61,
        "beds_available_estimate": 62,
        "icu_oiom_beds": 3,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 18.0,
        "phone_24h_sor": "+48 15 872 43 81",
        "email": "sekretariat@szpital-janow.pl",
        "specializations": "interna,chirurgia ogólna,ginekologia,pediatria",
    },
    {
        "facility_id": "SWD-001",
        "name": "SPZOZ w Świdniku",
        "short_name": "Szp. Świdnik",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Leśmiana 4",
        "city": "Świdnik",
        "postal_code": "21-040",
        "gmina": "Świdnik",
        "powiat": "świdnicki",
        "teryt_code": "0617011",
        "latitude": 51.221442,
        "longitude": 22.694568,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 18,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 110,
        "beds_total_physical": 130,
        "beds_occupied_pct": 0.59,
        "beds_available_estimate": 53,
        "icu_oiom_beds": 2,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 18.0,
        "phone_24h_sor": "+48 81 751 43 00",
        "email": "sekretariat@spzoz-swidnik.pl",
        "specializations": "interna,chirurgia ogólna,rehabilitacja",
    },
    {
        "facility_id": "OPL-001",
        "name": "Powiatowe Centrum Zdrowia w Opolu Lubelskim",
        "short_name": "PCZ Opole Lub.",
        "type": "szpital_ogólny",
        "operator": "PCZ Sp. z o.o.",
        "nfz_contract": True,
        "street": "ul. Szpitalna 8",
        "city": "Opole Lubelskie",
        "postal_code": "24-300",
        "gmina": "Opole Lubelskie",
        "powiat": "opolski",
        "teryt_code": "0612011",
        "latitude": 51.151756,
        "longitude": 21.975414,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 22,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 120,
        "beds_total_physical": 140,
        "beds_occupied_pct": 0.60,
        "beds_available_estimate": 56,
        "icu_oiom_beds": 3,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 18.0,
        "phone_24h_sor": "+48 81 827 22 20",
        "email": "sekretariat@pcz-opole.pl",
        "specializations": "interna,chirurgia ogólna,ginekologia",
    },
    {
        "facility_id": "BCH-001",
        "name": "SPZOZ w Bychawie — Szpital Powiatowy",
        "short_name": "Szp. Bychawa",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Piłsudskiego 28",
        "city": "Bychawa",
        "postal_code": "23-100",
        "gmina": "Bychawa",
        "powiat": "lubelski",
        "teryt_code": "0609011",
        "latitude": 51.013334,
        "longitude": 22.537361,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 12,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 80,
        "beds_total_physical": 100,
        "beds_occupied_pct": 0.55,
        "beds_available_estimate": 45,
        "icu_oiom_beds": 2,
        "ventilator_capable_beds": 1,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 1,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 12.0,
        "phone_24h_sor": "+48 81 566 02 30",
        "email": "sekretariat@spzoz-bychawa.pl",
        "specializations": "interna,chirurgia ogólna,rehabilitacja",
    },
    {
        "facility_id": "PON-001",
        "name": "Szpital Powiatowy w Poniatowej SPZOZ",
        "short_name": "Szp. Poniatowa",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Fabryczna 18",
        "city": "Poniatowa",
        "postal_code": "24-320",
        "gmina": "Poniatowa",
        "powiat": "opolski",
        "teryt_code": "0612011",
        "latitude": 51.173959,
        "longitude": 22.075761,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 10,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 70,
        "beds_total_physical": 85,
        "beds_occupied_pct": 0.52,
        "beds_available_estimate": 41,
        "icu_oiom_beds": 2,
        "ventilator_capable_beds": 1,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 1,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 12.0,
        "phone_24h_sor": "+48 81 820 45 00",
        "email": "sekretariat@szpital-poniatowa.pl",
        "specializations": "interna,rehabilitacja,opieka paliatywna",
    },
    {
        "facility_id": "BLZ-001",
        "name": "SPZOZ Nr 1 w Bełżycach",
        "short_name": "SPZOZ Bełżyce",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Lubelska 90",
        "city": "Bełżyce",
        "postal_code": "24-200",
        "gmina": "Bełżyce",
        "powiat": "lubelski",
        "teryt_code": "0609011",
        "latitude": 51.177018,
        "longitude": 22.292783,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 8,
        "decontamination_entry": False,
        "isolation_rooms": 0,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 50,
        "beds_total_physical": 60,
        "beds_occupied_pct": 0.50,
        "beds_available_estimate": 30,
        "icu_oiom_beds": 0,
        "ventilator_capable_beds": 0,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 1,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 12.0,
        "phone_24h_sor": "+48 81 516 28 00",
        "email": "sekretariat@spzoz-belzyce.pl",
        "specializations": "interna,rehabilitacja",
    },
    # ── Specjalistyczne / inne ────────────────────────────────────────────────
    {
        "facility_id": "PSY-001",
        "name": "Samodzielny Publiczny Wojewódzki Szpital Psychiatryczny w Radecznicy",
        "short_name": "Szp. Psych. Radecznica",
        "type": "szpital_specjalistyczny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "ul. Klasztorna 4",
        "city": "Radecznica",
        "postal_code": "22-463",
        "gmina": "Radecznica",
        "powiat": "zamojski",
        "teryt_code": "0620011",
        "latitude": 50.751438,
        "longitude": 22.825331,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 8,
        "decontamination_entry": False,
        "isolation_rooms": 2,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 260,
        "beds_total_physical": 280,
        "beds_occupied_pct": 0.88,
        "beds_available_estimate": 34,
        "icu_oiom_beds": 0,
        "ventilator_capable_beds": 0,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 0,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 84 681 82 21",
        "email": "sekretariat@szpitalpsych.radecznica.pl",
        "specializations": "psychiatria,psychogeriatria,leczenie uzależnień,rehabilitacja psychiatryczna",
    },
    {
        "facility_id": "PSY-002",
        "name": "Wojewódzki Szpital dla Nerwowo i Psychicznie Chorych w Suchowoli",
        "short_name": "Szp. Psych. Suchowola",
        "type": "szpital_specjalistyczny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "Suchowola 6",
        "city": "Suchowola",
        "postal_code": "21-013",
        "gmina": "Spiczyn",
        "powiat": "łęczyński",
        "teryt_code": "0609011",
        "latitude": 51.703946,
        "longitude": 22.727109,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 6,
        "decontamination_entry": False,
        "isolation_rooms": 2,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 300,
        "beds_total_physical": 320,
        "beds_occupied_pct": 0.90,
        "beds_available_estimate": 32,
        "icu_oiom_beds": 0,
        "ventilator_capable_beds": 0,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 0,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 24.0,
        "phone_24h_sor": "+48 81 757 62 12",
        "email": "sekretariat@szpitalsuchowola.pl",
        "specializations": "psychiatria,psychogeriatria,rehabilitacja psychiatryczna",
    },
    {
        "facility_id": "WOJ-001",
        "name": "6 Szpital Wojskowy z Przychodnią w Dęblinie",
        "short_name": "6SzW Dęblin",
        "type": "szpital_ogólny",
        "operator": "MON",
        "nfz_contract": True,
        "street": "ul. Szpitalna 2",
        "city": "Dęblin",
        "postal_code": "08-530",
        "gmina": "Dęblin",
        "powiat": "rycki",
        "teryt_code": "0615011",
        "latitude": 51.554104,
        "longitude": 21.856761,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 12,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 90,
        "beds_total_physical": 110,
        "beds_occupied_pct": 0.55,
        "beds_available_estimate": 50,
        "icu_oiom_beds": 2,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": True,
        "helipad_type": "naziemne",
        "helipad_night_capable": True,
        "backup_power": True,
        "backup_power_fuel_hours": 48.0,
        "phone_24h_sor": "+48 81 883 01 00",
        "email": "kancelaria@6szw.deblin.pl",
        "specializations": "interna,chirurgia ogólna,medycyna lotnicza,rehabilitacja",
    },
    {
        "facility_id": "KRS-002",
        "name": "SPZOZ Kraśnicki Szpital Powiatowy — Szpital Szczekarków",
        "short_name": "Szp. Szczekarków",
        "type": "szpital_ogólny",
        "operator": "SPZOZ",
        "nfz_contract": True,
        "street": "Szczekarków 134",
        "city": "Szczekarków",
        "postal_code": "23-206",
        "gmina": "Kraśnik",
        "powiat": "kraśnicki",
        "teryt_code": "0607011",
        "latitude": 50.98323,
        "longitude": 23.163392,
        "has_sor": True,
        "has_pediatric_sor": False,
        "has_izba_przyjec": False,
        "sor_throughput_per_day": 18,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 100,
        "beds_total_physical": 120,
        "beds_occupied_pct": 0.58,
        "beds_available_estimate": 50,
        "icu_oiom_beds": 2,
        "ventilator_capable_beds": 2,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": False,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 18.0,
        "phone_24h_sor": "+48 81 825 33 00",
        "email": "sekretariat@szpital-szczekarkow.pl",
        "specializations": "interna,chirurgia ogólna,rehabilitacja,geriatria",
    },
    {
        "facility_id": "CAR-001",
        "name": "Szpital 4Cardia w Kraśniku",
        "short_name": "4Cardia Kraśnik",
        "type": "szpital_specjalistyczny",
        "operator": "4Cardia Sp. z o.o.",
        "nfz_contract": True,
        "street": "ul. Urzędowska 30",
        "city": "Kraśnik",
        "postal_code": "23-200",
        "gmina": "Kraśnik",
        "powiat": "kraśnicki",
        "teryt_code": "0607011",
        "latitude": 50.96243,
        "longitude": 22.164188,
        "has_sor": False,
        "has_pediatric_sor": False,
        "has_izba_przyjec": True,
        "sor_throughput_per_day": 10,
        "decontamination_entry": False,
        "isolation_rooms": 1,
        "negative_pressure_rooms": 0,
        "beds_total_contracted": 60,
        "beds_total_physical": 70,
        "beds_occupied_pct": 0.65,
        "beds_available_estimate": 25,
        "icu_oiom_beds": 4,
        "ventilator_capable_beds": 4,
        "ecmo_available": False,
        "dialysis_stations": 0,
        "burn_unit": False,
        "neonatal_icu": False,
        "operating_rooms": 2,
        "polytrauma_capable": False,
        "ct_24_7": True,
        "mri_available": False,
        "helipad": False,
        "helipad_type": "brak",
        "helipad_night_capable": False,
        "backup_power": True,
        "backup_power_fuel_hours": 12.0,
        "phone_24h_sor": "+48 81 825 02 50",
        "email": "recepcja@4cardia.pl",
        "specializations": "kardiologia,kardiologia interwencyjna,angiologia",
    },
]


async def seed() -> None:
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with SessionLocal() as session:
        await session.execute(delete(HospitalRow))
        for h in HOSPITALS:
            session.add(HospitalRow(**h))
        await session.commit()

    print(f"Seeded {len(HOSPITALS)} hospitals into SQLite.")


if __name__ == "__main__":
    asyncio.run(seed())
